name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish to npmjs
        uses: JS-DevTools/npm-publish@v2.2.1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
